development: &default
  adapter: postgresql
  encoding: unicode
  database: docker_test_development
  min_messages: WARNING
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: db

test:
  <<: *default
  database: docker_test_test

production:
  <<: *default
  database: docker_test_production
  username: docker_test
  password: <%= ENV['DOCKER_TEST_DATABASE_PASSWORD'] %>
